name: erhan_ant_portfolio_v2
description: "Erhan Ant's personal portfolio website."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.5
  flutter_animate: ^4.5.2
  go_router: ^18.0.1
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  font_awesome_flutter: ^11.0.0
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences_platform_interface: ^2.4.2
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile.jpeg
    - assets/images/supportdesk_dashboard.png
    - assets/documents/Erhan_Ant_CV.pdf
